import type { EvChargingPageData } from "@/lib/ev-charging"
import { site } from "@/lib/site"

type PageConfig = Pick<
  EvChargingPageData,
  "eyebrow" | "title" | "description" | "bullets" | "stats" | "sections" | "faqs" | "related" | "ctaHeading" | "ctaBody" | "primaryActionLabel" | "primaryActionHref"
>

const electricalRelated = [
  { label: "Electrical Panel Upgrade", href: "/electrical-panel-upgrade" },
  { label: "Whole-House Rewiring", href: "/whole-house-rewiring" },
  { label: "Generator Installation", href: "/generator-installation" },
  { label: "Electrical Inspection", href: "/electrical-inspection" },
]

const emergencyRelated = [
  { label: "24/7 Emergency Electrician", href: "/emergency-electrician" },
  { label: "Power Outage Repair", href: "/power-outage-repair" },
  { label: "Sparking Outlet Repair", href: "/sparking-outlet-repair" },
  { label: "Storm Damage Repair", href: "/storm-damage-electrical-repair" },
]

const electricalPage = (page: PageConfig): EvChargingPageData => ({
  ...page,
  relatedHeading: "Explore related electrical services",
})

const emergencyPage = (page: PageConfig): EvChargingPageData => ({
  ...page,
  relatedHeading: "Explore related emergency electrical services",
})

export const electricalEmergencyPages: Record<string, EvChargingPageData> = {
  electrical: electricalPage({
    eyebrow: "Licensed electrical services",
    title: "Electrical work built around your home's safety and capacity.",
    description: "Licensed electricians for panels, wiring, lighting, generators, inspections, and repairs, with clear recommendations, permits, and workmanship backing.",
    ctaHeading: "Get an electrical plan built around your home and the work it actually needs.",
    ctaBody: "Talk with a licensed electrician, get a clear recommendation and fixed written quote before work begins.",
    bullets: ["Diagnosis before prescription", "Permits and inspections handled", "Up to 10-year workmanship guarantee"],
    stats: [{ label: "Service", value: "Residential + commercial" }, { label: "Estimate", value: "Free" }, { label: "Emergency", value: "24/7" }],
    sections: [
      { heading: "Every electrical decision starts with the actual condition of your home.", body: ["From the panel that sets your capacity to the wiring behind your walls, we assess the complete system before recommending work.", "That means a load calculation before a panel upgrade and a fault trace before a repair, so you only pay for what the problem requires."], points: ["Panels and service upgrades", "Wiring, circuits, outlets, and protection", "Lighting and smart controls", "Generators and backup power"] },
      { heading: "Code compliance is part of the work, not an add-on.", body: ["Permits, inspections, and current protection requirements are included whenever the job calls for them.", "You receive documentation that supports insurance, resale, and future electrical work."], points: ["Licensed, insured electricians", "Clear written scope and price", "Code-compliant materials", "Clean completion and documentation"] },
    ],
    faqs: [{ question: "How much does an electrician cost?", answer: "Small repairs often run $150-$450; dedicated circuits $250-$800; panel upgrades commonly $1,500-$4,000. You receive a written quote before work begins." }, { question: "Do you handle permits and inspections?", answer: "Yes. We file required permits, coordinate inspections, and provide the final documentation." }, { question: "How fast can you come out?", answer: "Standard assessments are scheduled within days. Genuine hazards such as sparking, burning smells, and home-side outages are dispatched through the 24/7 emergency line." }],
    related: electricalRelated,
  }),
  "electrical-panel-upgrade": electricalPage({
    eyebrow: "Panels & power",
    title: "Electrical panel upgrades for the loads your home has now.",
    description: "Modern 200-amp panel upgrades create capacity for EV chargers, batteries, heat pumps, and major appliances while replacing aging or unsafe equipment.",
    ctaHeading: "Get a panel recommendation based on a real load calculation.",
    ctaBody: "A licensed electrician will evaluate your service, capacity, and upgrade options before you commit.",
    bullets: ["Load calculation and panel assessment", "Utility coordination, permit, and inspection", "200-amp upgrades and safety replacements"],
    stats: [{ label: "Typical cost", value: "$1,500-$4,000" }, { label: "Common target", value: "200 amps" }, { label: "Install", value: "Often one day" }],
    sections: [
      { heading: "Your panel determines what your home can safely run at once.", body: ["Older 100-amp panels, fuse boxes, and recalled panel brands often cannot support modern electrical loads safely.", "A load calculation distinguishes a real capacity problem from one that can be solved with better circuit planning."], points: ["Frequent tripping or breakers that will not reset", "Flickering under large loads", "Fuse boxes and 60-100 amp service", "EV, battery, or appliance additions"] },
      { heading: "The project includes the work around the panel too.", body: ["Service entrance equipment, grounding, meter work, and utility disconnects can affect the scope and cost.", "We plan those dependencies before work begins, then handle permitting and inspection through completion."], points: ["Panel and compatible breakers", "Grounding and code-required protection", "Utility disconnect and reconnect coordination", "Permit and final inspection"] },
    ],
    faqs: [{ question: "How much does a 200-amp panel upgrade cost?", answer: "Most 100A-to-200A upgrades run $1,500-$4,000 depending on service entrance, meter work, and utility coordination." }, { question: "Do I need a panel upgrade for an EV charger?", answer: "Not always. A load calculation confirms whether your existing service has sufficient capacity." }, { question: "Will power be off during the upgrade?", answer: "Yes, usually for several hours while the panel is replaced and tested." }],
    related: electricalRelated,
  }),
  "whole-house-rewiring": electricalPage({
    eyebrow: "Wiring & circuits",
    title: "Whole-house rewiring that makes an older home safer and ready for modern life.",
    description: "Replace knob-and-tube, aluminum, cloth-insulated, or deteriorated wiring with grounded, code-compliant circuits and outlets.",
    ctaHeading: "Get a rewiring plan that protects your home without unnecessary disruption.",
    ctaBody: "A licensed electrician will assess your wiring, access routes, panel capacity, and practical phasing options.",
    bullets: ["Assessment and complete circuit plan", "Grounded wiring and modern protection", "Strategic access to limit wall disruption"],
    stats: [{ label: "Typical cost", value: "$8,000-$20,000+" }, { label: "Timeline", value: "Days to weeks" }, { label: "Protection", value: "Grounded circuits" }],
    sections: [{ heading: "Aging wiring is a safety issue, not just an inconvenience.", body: ["Knob-and-tube, aluminum, and cloth-insulated wiring degrade over time and can create a serious fire risk at connections.", "Rewiring replaces those risks with grounded circuits, modern AFCI protection, and capacity for today's electrical loads."], points: ["Warm outlets or frequent trips", "Two-prong outlets throughout", "Flickering lights and buzzing", "Homes built before 1970 without a rewire"] }, { heading: "Experienced rewiring is staged, strategic work.", body: ["We use attics, basements, crawl spaces, and existing wall cavities wherever possible, making small patchable openings only when necessary.", "Rooms are sequenced to keep the home as livable as possible during the project."], points: ["Room-by-room phasing", "Panel upgrade if the design requires it", "Permits and inspection", "Clean finish and wiring documentation"] }],
    faqs: [{ question: "How do I know if I need rewiring?", answer: "Knob-and-tube or aluminum wiring, warm outlets, frequent tripping, or persistent flickering are reasons to schedule an inspection." }, { question: "Do I need to move out?", answer: "Usually not. Most projects are completed in stages while homeowners remain in the home." }, { question: "How long does rewiring take?", answer: "Most projects take several days to about two weeks depending on the home and access." }],
    related: electricalRelated,
  }),
  "generator-installation": electricalPage({
    eyebrow: "Generators & backup",
    title: "Standby generator installation for automatic backup when the grid fails.",
    description: "Whole-home and essential-circuit generators sized to your loads, fuel supply, site conditions, and transfer-switch requirements.",
    ctaHeading: "Get a standby generator sized to the circuits you need during an outage.",
    ctaBody: "A licensed electrician will evaluate loads, siting, fuel, and transfer-switch options before work begins.",
    bullets: ["Load assessment and correct sizing", "Generator, pad, and transfer switch", "Fuel and electrical coordination"],
    stats: [{ label: "Typical cost", value: "$5,000-$15,000" }, { label: "Response", value: "Automatic" }, { label: "Fuel", value: "Gas or propane" }],
    sections: [{ heading: "Sizing begins with what you need to keep running.", body: ["Essential backup often covers refrigeration, lighting, furnace equipment, and a well pump. Whole-home backup can add central A/C and other larger loads.", "Motor starting surge, not just running wattage, is part of every correct sizing calculation."], points: ["Essential or whole-home coverage", "Motor-starting load calculation", "Natural gas or propane review", "Automatic transfer-switch selection"] }, { heading: "Siting and fuel capacity decide whether the system will work when needed.", body: ["Generators need code-compliant clearance from openings, meters, and service paths. Natural gas and propane each have different capacity and logistics requirements.", "We settle those questions during the site visit, then handle installation, permitting, testing, and commissioning."], points: ["Code-compliant placement", "Fuel supply review", "Permit and inspection", "Start-up testing"] }],
    faqs: [{ question: "What size generator do I need?", answer: "A load assessment matches capacity to the circuits you want to back up. Whole-home systems with central A/C are commonly 18-26kW." }, { question: "Standby or portable generator?", answer: "Standby generators start automatically and can run for days; portable generators cost less but are manual and need refueling." }, { question: "How often does a standby generator need service?", answer: "An annual maintenance visit keeps it reliable, alongside its scheduled self-test." }],
    related: electricalRelated,
  }),
  "circuit-breaker-replacement": electricalPage({
    eyebrow: "Panels & protection",
    title: "Circuit breaker replacement that finds the fault behind the trip.",
    description: "Repeated trips, breakers that will not reset, and warm breakers can signal overloads, shorts, failing equipment, or a worn-out breaker.",
    ctaHeading: "Get the cause of a tripping breaker diagnosed before replacing anything.",
    ctaBody: "A licensed electrician will test the circuit, inspect the connection, and recommend the right repair.",
    bullets: ["Root-cause circuit diagnosis", "Standard, AFCI, and GFCI breakers", "Often same-day for single breakers"],
    stats: [{ label: "Typical visit", value: "Same day" }, { label: "Protection", value: "AFCI + GFCI" }, { label: "Approach", value: "Diagnose first" }],
    sections: [{ heading: "A tripping breaker is often doing its job.", body: ["The breaker may be responding to an overloaded circuit, short, loose connection, or failing appliance rather than failing itself.", "Replacing it without testing can leave the underlying hazard in place."], points: ["Overloaded circuits", "Shorts and ground faults", "Loose or corroded terminations", "Worn or defective breakers"] }, { heading: "Replacement includes the inspection around it.", body: ["We test the circuit under load, inspect bus and termination condition, and install the correct breaker type for the panel and circuit.", "Where applicable, the repair can bring required AFCI or GFCI protection into the scope."], points: ["Circuit testing", "Heat and termination inspection", "Correct listed breaker type", "Protection upgrades where required"] }],
    faqs: [{ question: "Why does my breaker keep tripping?", answer: "Usually an overload, short, ground fault, failing appliance, or failed breaker. Testing identifies the cause." }, { question: "Is a tripping breaker dangerous?", answer: "The trip protects you, but repeated trips point to an issue that should be diagnosed promptly." }, { question: "Can I replace it myself?", answer: "Work inside a live panel is dangerous. A licensed electrician ensures the correct breaker and safe installation." }],
    related: electricalRelated,
  }),
  "lighting-installation": electricalPage({
    eyebrow: "Lighting",
    title: "Lighting installation that makes every room work better.",
    description: "Recessed lighting, fixtures, under-cabinet and landscape lighting, plus smart dimmers and controls installed cleanly and to code.",
    ctaHeading: "Get a lighting plan that fits how you use each room.",
    ctaBody: "A licensed electrician will help plan layout, controls, color temperature, and clean wiring routes.",
    bullets: ["Recessed, fixture, and accent lighting", "Smart switches and dimmers", "LED-efficient designs"],
    stats: [{ label: "Recessed lights", value: "$150-$300 each" }, { label: "Room projects", value: "$800-$3,000" }, { label: "Controls", value: "Smart-ready" }],
    sections: [{ heading: "Good lighting uses more than one source.", body: ["Ambient light fills a room, task light supports work, and accent light gives a space depth and character.", "Layering even two sources with dimmers can transform a room without adding much wiring complexity."], points: ["Recessed layouts", "Pendants and chandeliers", "Under-cabinet task lighting", "Exterior and landscape lighting"] }, { heading: "Controls make the design useful every day.", body: ["Dimmers extend LED life, reduce energy use, and turn a room into multiple settings. Smart controls add scheduling and scene control while preserving normal switch operation.", "We match the control hardware to your wiring, fixtures, and preferred ecosystem."], points: ["Dimmers and three-way controls", "Smart switch compatibility", "LED flicker prevention", "Code-compliant boxes and wiring"] }],
    faqs: [{ question: "Can you install smart lighting?", answer: "Yes. We install and configure compatible smart switches, dimmers, and fixtures." }, { question: "Can recessed lights be added to an existing ceiling?", answer: "Usually. We inspect above-ceiling access and plan clean placement with minimal patching." }, { question: "Can you help choose light placement?", answer: "Yes. The assessment covers fixture placement, lighting layers, color temperature, and controls." }],
    related: electricalRelated,
  }),
  "commercial-lighting-retrofit": electricalPage({
    eyebrow: "Commercial lighting",
    title: "Commercial LED retrofits that lower operating costs without disrupting work.",
    description: "LED retrofits for offices, retail, warehouses, parking areas, and refrigerated spaces, with photometric planning, rebate support, and phased installation.",
    ctaHeading: "Get a lighting retrofit plan that improves light levels and the operating budget.",
    ctaBody: "Schedule an on-site assessment for fixture analysis, savings estimates, rebate capture, and a disruption-conscious work plan.",
    bullets: ["50-70% lower lighting energy", "Utility rebate documentation", "After-hours, zone-by-zone crews"],
    stats: [{ label: "Energy reduction", value: "50-70%" }, { label: "Typical payback", value: "1.5-3 yrs" }, { label: "Rebates", value: "$10-$50/fixture" }],
    sections: [{ heading: "The savings compound beyond the utility bill.", body: ["LED fixtures reduce wattage and dramatically cut relamping labor, so the project keeps returning value after installation.", "A photometric check helps ensure better light quality and coverage rather than simply lower consumption."], points: ["Warehouse highbays", "Office troffers and occupancy sensors", "Retail color quality", "Parking and exterior lighting"] }, { heading: "Retrofits are planned around your operation.", body: ["Occupied buildings are completed after hours and by zone so workspaces remain functional each morning.", "We manage old-lamp recycling documentation and the paperwork utilities require for rebates."], points: ["Phased scheduling", "After-hours installation", "Recycling manifests", "Rebate filing support"] }],
    faqs: [{ question: "What is the typical LED retrofit payback?", answer: "Offices and retail commonly see 1.5-3 years from energy and maintenance savings; high-hour warehouse projects can be faster." }, { question: "Can you retrofit occupied buildings?", answer: "Yes. We use after-hours, phased work to keep tenants and operations undisturbed." }, { question: "Retrofit kits or full fixture replacement?", answer: "Both can be right. We compare the options and recommend the one that makes economic and lighting sense." }],
    related: [{ label: "Commercial Electrical", href: "/commercial-electrical" }, { label: "Commercial Electrician", href: "/commercial-electrician" }, { label: "Electrical Inspection", href: "/electrical-inspection" }, { label: "Electrical Services", href: "/electrical" }],
  }),
  "electrical-inspection": electricalPage({
    eyebrow: "Safety & inspection",
    title: "Electrical inspections that turn unknown risks into a clear priority list.",
    description: "Licensed inspections of panels, grounding, wiring, outlets, and protective devices for homebuyers, renovations, new loads, and older homes.",
    ctaHeading: "Get a clear electrical safety and capacity assessment for your home.",
    ctaBody: "A licensed electrician will inspect the system and provide prioritized recommendations with real repair options.",
    bullets: ["Panel, grounding, wiring, and outlets", "Hazards and code issues prioritized", "Written findings and recommendations"],
    stats: [{ label: "Homebuyer visits", value: "$200-$450" }, { label: "Older homes", value: "Every 10 yrs" }, { label: "Report", value: "Written" }],
    sections: [{ heading: "An inspection looks past what is visible at the wall.", body: ["We evaluate panel condition, breaker integrity, grounding and bonding, wiring condition, and required protection.", "That matters before buying a home, after a remodel, or before adding an EV charger, battery, or other major load."], points: ["Panel capacity and heat damage", "Grounding and bonding", "Wiring type and age", "GFCI and AFCI protection"] }, { heading: "The result is a practical repair roadmap.", body: ["Findings are prioritized as urgent, soon, and fine-for-now so you can act on actual risk rather than a vague checklist.", "Most homes need less work than owners fear; a few contain serious conditions that are best found early."], points: ["Double-tapped breakers", "Open junction boxes", "Heat-stressed connections", "Recalled panels and unsafe wiring"] }],
    faqs: [{ question: "When should I get an electrical inspection?", answer: "Before buying a home, after a major renovation, before adding large loads, and roughly every 10 years for older homes." }, { question: "Do I get a written report?", answer: "Yes. You receive detailed findings and clear recommendations with urgent safety issues prioritized." }, { question: "Can an inspection support a panel upgrade decision?", answer: "Yes. It evaluates current capacity and identifies whether an upgrade is needed for planned loads." }],
    related: electricalRelated,
  }),
  emergency: emergencyPage({
    eyebrow: "24/7 emergency electrical",
    title: "Electrical emergencies that cannot wait until morning.",
    description: "Licensed emergency electricians available 24/7 for sparking, burning smells, hot panels, home-side outages, water intrusion, and storm damage.",
    ctaHeading: "For an electrical emergency, call now for immediate triage and dispatch.",
    ctaBody: "If safe, turn off the affected breaker. Do not touch scorched or wet equipment; leave the home if a burning smell intensifies.",
    bullets: ["24/7 phone triage and dispatch", "Up-front diagnosis and repair pricing", "Licensed local electricians"],
    stats: [{ label: "Response", value: "24/7" }, { label: "Triage", value: "Immediate" }, { label: "Priority", value: "Fire + shock hazards" }],
    sections: [{ heading: "Call now for fire, shock, and serious outage risks.", body: ["Burning smells, sparking, hot or buzzing panels, exposed wires, and water in electrical equipment require immediate attention.", "A whole-home outage when neighbors still have power can also indicate a dangerous home-side service failure."], points: ["Smoke or burning smell", "Sparking or repeated popping", "Hot panel or scorched breaker", "Downed or exposed property wires"] }, { heading: "The first priority is making the situation safe.", body: ["Our dispatcher helps you assess urgency and gives practical safety direction while arranging a licensed electrician.", "You receive a diagnosis and repair price before work begins, even in an overnight emergency."], points: ["Switch off the affected breaker if safe", "Do not reset repeatedly tripping breakers", "Do not touch wet or scorched equipment", "Leave if smoke or odor intensifies"] }],
    faqs: [{ question: "What counts as an electrical emergency?", answer: "Burning smells, sparking, hot panels, exposed live wires, water contact with electrical equipment, and home-side whole-house outages all warrant immediate triage." }, { question: "Do you answer 24/7?", answer: "Yes. Nights, weekends, and holidays are triaged and genuine safety hazards are dispatched immediately." }, { question: "What should I do while waiting?", answer: "If it is safe, turn off the affected breaker or main. Do not touch scorched or wet equipment." }],
    related: emergencyRelated,
  }),
  "emergency-electrician": emergencyPage({
    eyebrow: "24/7 emergency electrician",
    title: "A licensed emergency electrician when the electrical problem cannot wait.",
    description: "Fast 24/7 triage and dispatch for problems that risk fire, shock, or leave your home unlivable, with diagnosis and price explained before repair.",
    ctaHeading: "Call now to speak with an emergency electrical dispatcher.",
    ctaBody: "Describe the symptom, make the area safe if you can, and get a real ETA for a licensed electrician.",
    primaryActionLabel: "Call the 24/7 emergency line",
    primaryActionHref: site.phoneHref,
    bullets: ["Sparking, smoke, hot panels, and outages", "Emergency triage before dispatch", "Most repairs resolved in one visit"],
    stats: [{ label: "Availability", value: "24/7" }, { label: "Dispatch", value: "Nationwide" }, { label: "Pricing", value: "Quoted first" }],
    sections: [{ heading: "Certain electrical symptoms are never wait-and-see problems.", body: ["Smoke, burning odor, sparking, exposed wires, and water intrusion can escalate quickly into fire or shock risk.", "Our dispatch team distinguishes a genuine hazard from a repair that can safely wait until the next business day."], points: ["Burning smell or smoke", "Sparking or buzzing panel", "Hot equipment", "Utility-confirmed home-side outage"] }, { heading: "Safety comes before troubleshooting.", body: ["If it is safe to reach the panel, turn off the affected breaker or the main if you cannot identify it.", "Do not touch wet or scorched equipment, and leave the home if an odor intensifies."], points: ["Phone triage", "Clear safety guidance", "Licensed electrician dispatch", "Up-front repair quote"] }],
    faqs: [{ question: "How fast can an electrician arrive?", answer: "Response depends on location and time; dispatch provides a real ETA, with genuine hazards prioritized." }, { question: "How much does an emergency electrician cost?", answer: "You receive the diagnostic and repair price before work starts, with no surprise multiplier." }, { question: "What should I do while I wait?", answer: "Shut off the affected breaker if safe and do not touch scorched or wet equipment." }],
    related: emergencyRelated,
  }),
  "power-outage-repair": emergencyPage({
    eyebrow: "24/7 outage repair",
    title: "Power outage repair when the problem is on your side of the meter.",
    description: "If your neighbors have power but your home does not, we diagnose failed mains, panels, breakers, meter bases, and service-entrance connections 24/7.",
    ctaHeading: "Get a home-side power outage diagnosed and repaired safely.",
    ctaBody: "Call for immediate triage if the utility confirms the issue is not on its equipment.",
    bullets: ["Main breaker and panel diagnosis", "Service entrance and meter base checks", "Utility reconnection coordination"],
    stats: [{ label: "Availability", value: "24/7" }, { label: "Risk", value: "Partial outages" }, { label: "Scope", value: "Meter to panel" }],
    sections: [{ heading: "A partial outage can signal a dangerous service failure.", body: ["Half the home dead, dimming or surging lights, and loss of one 240-volt service leg can point to a failed main connection that arcs and overheats.", "That should be treated as urgent, not simply as an inconvenience."], points: ["Failed or tripped main breaker", "Panel bus and branch breakers", "Meter base connections", "Service-entrance equipment"] }, { heading: "We isolate the fault and coordinate the next step.", body: ["The utility handles its own lines; we diagnose and repair the equipment on your property.", "When a disconnect or reconnect is required, we coordinate the utility process after the repair is complete."], points: ["Home-side fault tracing", "Safe repair and testing", "Permit when required", "Utility reconnect coordination"] }],
    faqs: [{ question: "Why is my power out when neighbors have power?", answer: "It often means a failed main breaker, damaged service entrance, meter-base issue, or a utility drop issue specific to your home." }, { question: "Is half the house being out serious?", answer: "Yes. Losing one service leg can indicate a failing connection that may arc and overheat." }, { question: "The utility says it is my side. What now?", answer: "We diagnose from the weatherhead to the panel, make the repair, and coordinate any required reconnect." }],
    related: emergencyRelated,
  }),
  "storm-damage-electrical-repair": emergencyPage({
    eyebrow: "Storm response",
    title: "Storm damage electrical repair that gets your home ready for reconnection.",
    description: "Emergency make-safe, service mast, weatherhead, meter base, panel, and surge-damage repairs with utility coordination and insurance-ready documentation.",
    ctaHeading: "Get storm-damaged electrical equipment made safe and ready for utility reconnection.",
    ctaBody: "Call now for emergency triage, repair coordination, and documentation for your insurance claim.",
    bullets: ["Mast, weatherhead, meter-base, and panel repair", "Utility disconnect and reconnect coordination", "Insurance-ready photos and itemized documentation"],
    stats: [{ label: "Priority", value: "Make-safe first" }, { label: "Response", value: "24/7" }, { label: "Documentation", value: "Insurance-ready" }],
    sections: [{ heading: "The utility restores its lines; your service equipment is your responsibility.", body: ["Storms can damage the mast, weatherhead, meter base, service cable, and panel attached to your home. A licensed electrician repairs those components before the utility reconnects service.", "We manage the repair sequence from emergency make-safe through reconnection."], points: ["Bent or damaged service mast", "Weatherhead and cable damage", "Meter base pulled from the wall", "Lightning and surge damage"] }, { heading: "Flooded electrical equipment must be replaced, not dried out.", body: ["Water inside panels and breakers causes hidden corrosion and contamination that can lead to arcing later.", "We document damaged equipment clearly for the insurer and replace unsafe components to current requirements."], points: ["Flooded panel assessment", "Safe replacement recommendations", "Insurance photos and cause notes", "Itemized repair invoice"] }],
    faqs: [{ question: "Who fixes a service line pulled from my house?", answer: "The utility fixes its line; the mast, weatherhead, and meter base on your property require licensed electrical repair before reconnection." }, { question: "Is a wet panel safe?", answer: "No. Keep the power off and have it inspected before re-energizing; submerged equipment often requires replacement." }, { question: "Will insurance cover the repair?", answer: "Storm-caused electrical damage is commonly covered. We provide the photos and itemized documentation adjusters need." }],
    related: emergencyRelated,
  }),
  "sparking-outlet-repair": emergencyPage({
    eyebrow: "Urgent outlet repair",
    title: "Sparking outlet and panel repair before arcing becomes a fire.",
    description: "Repeated sparks, popping, scorch marks, warmth, or any panel sparking require fast diagnosis of the connection and circuit behind the symptom.",
    ctaHeading: "Stop using the circuit and call for urgent sparking-outlet repair.",
    ctaBody: "If safe, turn off the affected breaker. A licensed electrician will locate and repair the arcing connection.",
    bullets: ["Outlet, switch, and panel arcing repair", "Heat-damage inspection", "AFCI and GFCI upgrades where appropriate"],
    stats: [{ label: "Response", value: "24/7" }, { label: "Hazard", value: "Arcing" }, { label: "Action", value: "Turn circuit off" }],
    sections: [{ heading: "Repeated sparks are not normal contact arcing.", body: ["A small blue spark when plugging in can happen occasionally. Repeated or yellow sparks, popping, scorch marks, or sparks from the panel indicate dangerous arcing.", "Turn off the circuit and arrange a repair promptly."], points: ["Worn outlet contacts", "Loose terminations", "Overloaded circuits", "Damaged insulation or corrosion"] }, { heading: "The repair includes what is behind the outlet.", body: ["We inspect conductors for heat damage, repair or re-terminate wiring, replace the device, and test the circuit under load.", "Where needed, we add appropriate arc-fault or ground-fault protection."], points: ["Circuit inspection", "Conductor repair", "New listed device", "Protection upgrade evaluation"] }],
    faqs: [{ question: "Is a sparking outlet dangerous?", answer: "Repeated or large sparks, scorch marks, or a burning smell indicate dangerous arcing. Turn off the breaker and arrange repair." }, { question: "Why did the outlet spark and stop working?", answer: "A burned connection, failed device, or tripped circuit is common. The wiring must be inspected for overheating." }, { question: "Does a single small spark need repair?", answer: "A one-time small plug-in spark is often harmless; repeated sparking, warmth, marks, or odors are not." }],
    related: emergencyRelated,
  }),
  "burning-smell-electrical": emergencyPage({
    eyebrow: "Urgent inspection",
    title: "A burning or fishy electrical smell is an urgent warning, not a mystery to ignore.",
    description: "Thermal imaging and circuit testing identify overheating wiring, loose connections, failing breakers, and hidden hot spots before they become a fire.",
    ctaHeading: "For a burning electrical smell, make the area safe and call for urgent inspection.",
    ctaBody: "Turn off the suspect circuit if safe. Do not ignore an odor that fades; intermittent overheating can still be dangerous.",
    bullets: ["Thermal imaging and circuit testing", "Hidden-source fault tracing", "24/7 urgent response"],
    stats: [{ label: "Response", value: "24/7" }, { label: "Risk", value: "Fire precursor" }, { label: "Method", value: "Thermal testing" }],
    sections: [{ heading: "Burning insulation has a recognizable warning smell.", body: ["People often describe it as fishy, acrid, or like burning plastic. It can come from a failing panel connection, overloaded outlet, junction box, motor, or transformer.", "The source is often hidden, which is why a professional trace matters."], points: ["Failing breaker or burned lug", "Loose outlets and switches", "Overheating junction boxes", "Failing motors or transformers"] }, { heading: "An intermittent smell is still a reason to act now.", body: ["Heat problems often follow electrical load, then temporarily disappear while the damaged connection continues degrading.", "Thermal imaging, circuit isolation, and load testing usually locate the hot spot without exploratory wall removal."], points: ["Turn off the suspect breaker if safe", "Do not touch scorched equipment", "Leave if smoke or odor intensifies", "Targeted rather than exploratory repair"] }],
    faqs: [{ question: "Why does my house smell like burning plastic or fish?", answer: "It often indicates overheating insulation, a loose connection, overloaded wiring, or a failing breaker and needs urgent inspection." }, { question: "What should I do right now?", answer: "If safe, turn off the suspect breaker or main. Leave the home if the smell intensifies or you see smoke, then call." }, { question: "The smell disappeared. Am I in the clear?", answer: "No. Overheating can be intermittent and each heat cycle can worsen the connection." }],
    related: emergencyRelated,
  }),
}
