// Migrates the company's own rebate listings from the legacy site into a typed
// dataset at lib/rebates.ts. It is a faithful copy of chargehomesolutions.com's
// /rebates pages (our own content); every program keeps its official source URL.
//
// Run from the repo root:  node scripts/migrate-rebates.mjs
// Bump REBATES_VERIFIED below whenever you refresh (aim for quarterly).

import fs from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"

const REBATES_VERIFIED = "August 2026"
const BASE = "https://chargehomesolutions.com"
const UA = { headers: { "User-Agent": "Mozilla/5.0" } }
const OUT = path.join(path.dirname(fileURLToPath(import.meta.url)), "..", "lib", "rebates.ts")

const decode = (s) =>
  s
    .replace(/&amp;/g, "&")
    .replace(/&#x27;|&#39;/g, "'")
    .replace(/&quot;/g, '"')
    .replace(/&nbsp;/g, " ")
    .replace(/&mdash;/g, "—")
    .replace(/&ndash;/g, "–")
    .replace(/&gt;/g, ">")
    .replace(/&lt;/g, "<")
    .replace(/<[^>]+>/g, "")
    .replace(/\s+/g, " ")
    .trim()

async function get(url) {
  const r = await fetch(url, UA)
  if (!r.ok) throw new Error(`${url} -> HTTP ${r.status}`)
  return r.text()
}

const stateName = (slug) =>
  slug
    .split("-")
    .map((w, i) => (i > 0 && w === "of" ? "of" : w[0].toUpperCase() + w.slice(1)))
    .join(" ")

const CARD =
  /<div class="rounded-xl border border-white\/10 bg-\[#0a1120\] p-5">([\s\S]*?)(?=<div class="rounded-xl border border-white\/10 bg-\[#0a1120\] p-5">|<\/main>|<footer)/g

function parseState(html) {
  const programs = []
  for (const m of html.matchAll(CARD)) {
    const c = m[1]
    const badge = c.match(/<span class="rounded bg-white\/10[^"]*"[^>]*>([\s\S]*?)<\/span>/)
    const name = c.match(/<h3[^>]*>([\s\S]*?)<\/h3>/)
    const amount = c.match(/<span class="shrink-0 rounded-lg bg-brand\/15[^"]*"[^>]*>([\s\S]*?)<\/span>/)
    const ps = [...c.matchAll(/<p class="mt-1\.5 text-sm leading-relaxed[^"]*">([\s\S]*?)<\/p>/g)].map((p) =>
      decode(p[1]),
    )
    const url = c.match(/<a href="(https?:\/\/[^"]+)"/)
    if (!name) continue
    programs.push({
      category: badge ? decode(badge[1]) : "Utility",
      name: decode(name[1]),
      amount: amount ? decode(amount[1]) : "",
      eligibility: ps[0] || "",
      detail: ps[1] || null,
      officialUrl: url ? url[1] : "",
    })
  }
  return programs
}

const index = await get(`${BASE}/rebates/`)
const slugs = [...new Set([...index.matchAll(/href="\/rebates\/([a-z-]+)\/"/g)].map((m) => m[1]))].filter(
  (s) => s.length > 1,
)

const data = []
for (const slug of slugs) {
  try {
    const programs = parseState(await get(`${BASE}/rebates/${slug}/`))
    if (programs.length === 0) continue // skip category index pages
    data.push({ slug, state: stateName(slug), programs })
    process.stdout.write(`${slug}:${programs.length} `)
  } catch (e) {
    console.log(`\nFAIL ${slug}: ${e.message}`)
  }
}
console.log("\n")

data.sort((a, b) => a.state.localeCompare(b.state))
const totalPrograms = data.reduce((n, s) => n + s.programs.length, 0)

const file = `// AUTO-GENERATED by scripts/migrate-rebates.mjs — do not hand-edit.
// Faithful migration of chargehomesolutions.com/rebates (our own content);
// every program keeps its official source URL so users can verify. Refresh quarterly.

export type RebateCategory = "Federal" | "State" | "Utility"

export type RebateProgram = {
  category: RebateCategory
  name: string
  /** Headline dollar figure, verbatim from the source (e.g. "Up to $2,500"). */
  amount: string
  /** Who qualifies / where it applies. */
  eligibility: string
  /** Extra detail, when the source provided a second line. */
  detail: string | null
  /** Official program page for the user to verify eligibility. */
  officialUrl: string
}

export type StateRebates = {
  slug: string
  state: string
  programs: RebateProgram[]
}

/** When this snapshot was captured from the source pages. */
export const REBATES_VERIFIED = ${JSON.stringify(REBATES_VERIFIED)}

export const rebateTotals = {
  states: ${data.length},
  programs: ${totalPrograms},
} as const

export const rebates: StateRebates[] = ${JSON.stringify(data, null, 2)}

const bySlug = new Map(rebates.map((s) => [s.slug, s]))

export function getStateRebates(slug: string): StateRebates | undefined {
  return bySlug.get(slug)
}

/** Lightweight list for the index page and selectors. */
export function rebateStateList(): { slug: string; state: string; count: number }[] {
  return rebates.map((s) => ({ slug: s.slug, state: s.state, count: s.programs.length }))
}
`

fs.writeFileSync(OUT, file)
console.log(`wrote ${OUT}\nstates: ${data.length}  programs: ${totalPrograms}`)
